---
- name: Create directory
  file:
    path: "{{ item }}"
    owner: root
    state: directory
  with_items:
    - /etc/matrix-config

- name: Copy Service Account
  template:
    src: etc/matrix-config/matrix-cloudsql.json.j2
    dest: /etc/matrix-config/matrix-cloudsql.json
    mode: 0755
    owner: root

- name: Copy systemd service
  template:
    src: "etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
  register: systemd
  with_items:
    - cloudsql-proxy.service

- name: Ensure systemd service
  systemd:
    name: "{{ item.item }}"
    daemon_reload: yes
    enabled: yes
    state: "{{ (item.changed) | ternary('restarted', 'started') }}"
  with_items: "{{ systemd.results }}"
