---
- name: apt-get update
  apt:
    update_cache: yes

- name: Install python
  apt:
    name: python-requests
    state: present

- name: Install docker
  apt:
    name: docker.io
    state: present

- name: Install python3-docker
  apt:
    name: python3-docker
    state: present

- name: Install python-docker
  apt:
    name: python-docker
    state: present

- name: Start docker
  systemd:
    name: docker
    state: started

